### ISSUE TITLE
`fatal error: invalid heap pointer` initializing testnet database

### ISSUE THREAD

**Issue by evanwagner1** [conformal/btcd#195]
I was doing an initial build of the testnet database, and it was running fine for hours and then this suddenly appeared. I've restarted the database and it's working fine.

Log:
```
22:55:47 2014-12-21 [INF] BMGR: Processed 47 blocks in the last 10.39s (8000 transactions, height 269484, 2014-07-17 22:09:26 +0200 CEST)
runtime: garbage collector found invalid heap pointer *(0xc20827ae70+0x120)=0xc20ac11000 span=0xc20ac00000-0xc20ac11000-0xc20ac12000 state=0
fatal error: invalid heap pointer
runtime stack:
runtime.throw(0xe27d23)
    /usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7f091f5f0968 sp=0x7f091f5f0938
scanblock(0xc20827ae70, 0x168, 0xc211e8)
    /usr/local/go/src/runtime/mgc0.c:378 +0x551 fp=0x7f091f5f0aa8 sp=0x7f091f5f0968
scanframe(0x7f091f5f0bb0, 0x0, 0x101)
    /usr/local/go/src/runtime/mgc0.c:719 +0x164 fp=0x7f091f5f0b18 sp=0x7f091f5f0aa8
runtime.gentraceback(0x4b7100, 0xc20827abe8, 0x0, 0xc20810f0e0, 0x0, 0x0, 0x7fffffff, 0x7f091f5f0c60, 0x0, 0x0, ...)
    /usr/local/go/src/runtime/traceback.go:311 +0x7a8 fp=0x7f091f5f0c08 sp=0x7f091f5f0b18
scanstack(0xc20810f0e0)
    /usr/local/go/src/runtime/mgc0.c:777 +0x21c fp=0x7f091f5f0c78 sp=0x7f091f5f0c08
markroot(0xc208010000, 0x1d)
    /usr/local/go/src/runtime/mgc0.c:553 +0xe7 fp=0x7f091f5f0cd8 sp=0x7f091f5f0c78
runtime.parfordo(0xc208010000)
    /usr/local/go/src/runtime/parfor.c:91 +0x13b fp=0x7f091f5f0d58 sp=0x7f091f5f0cd8
runtime.gchelper()
    /usr/local/go/src/runtime/mgc0.c:1185 +0x4a fp=0x7f091f5f0d80 sp=0x7f091f5f0d58
stopm()
    /usr/local/go/src/runtime/proc.c:1181 +0x158 fp=0x7f091f5f0da0 sp=0x7f091f5f0d80
findrunnable(0xc208014400)
    /usr/local/go/src/runtime/proc.c:1487 +0x562 fp=0x7f091f5f0dd8 sp=0x7f091f5f0da0
schedule()
    /usr/local/go/src/runtime/proc.c:1575 +0x151 fp=0x7f091f5f0e08 sp=0x7f091f5f0dd8
runtime.gosched_m(0xc2080005a0)
    /usr/local/go/src/runtime/proc.c:1674 +0xac fp=0x7f091f5f0e28 sp=0x7f091f5f0e08
runtime.mcall(0x4ad274)
    /usr/local/go/src/runtime/asm_amd64.s:186 +0x5a fp=0x7f091f5f0e38 sp=0x7f091f5f0e28

goroutine 1 [chan receive, 17 minutes]:
runtime.gopark(0x4aee20, 0xc208054118, 0xb10970, 0xc)
    /usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801cd38 sp=0xc20801cd08
runtime.goparkunlock(0xc208054118, 0xb10970, 0xc)
    /usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801cd60 sp=0xc20801cd38
runtime.chanrecv(0x8fcd60, 0xc2080540c0, 0x0, 0x40a901, 0x0)
    /usr/local/go/src/runtime/chan.go:410 +0x452 fp=0xc20801ce00 sp=0xc20801cd60
runtime.chanrecv1(0x8fcd60, 0xc2080540c0, 0x0)
    /usr/local/go/src/runtime/chan.go:311 +0x2b fp=0xc20801ce30 sp=0xc20801ce00
main.btcdMain(0x0, 0x0, 0x0)
    /home/blanket/go/src/github.com/conformal/btcd/btcd.go:122 +0xad0 fp=0xc20801cf40 sp=0xc20801ce30
main.main()
    /home/blanket/go/src/github.com/conformal/btcd/btcd.go:151 +0x62 fp=0xc20801cf98 sp=0xc20801cf40
runtime.main()
    /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20801cfe0 sp=0xc20801cf98
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801cfe8 sp=0xc20801cfe0

goroutine 2 [force gc (idle), 17 minutes]:
runtime.gopark(0x4aee20, 0xf2a470, 0xb15030, 0xf)
    /usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
[...]
```

**Comment by davecgh** [comment]
Go 1.4.1 has been released and includes the fix for this.
